title: "Roger's Notes"
description: My personal notes
author: "Roger Bolsius"

remote_theme: jekyll/minima

# base_url: /gh-pages-minima-starter
# repository: jsanz/gh-pages-minima-starter


# Minima: show excerpts in the frontpage
# show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  skin: auto

# Minima: custom header links
# header_pages:
#   - _pages/frontpage.md
#   - _pages/about.md
#   - _pages/archive.md

# include:
#     - _pages

exclude: 
    - .gitignore
